name: Build and Push Docker Images

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        base-image-tag:
          - "1.4.0-py3.8.13-cuda10.1-ubuntu18.04"
          - "1.5.1-py3.8.13-cuda10.2-ubuntu18.04"
          - "1.6.0-py3.8.13-cuda10.2-ubuntu18.04"
          - "1.7.1-py3.9.12-cuda11.0-ubuntu18.04"
          - "1.8.1-py3.9.12-cuda11.1-ubuntu20.04"
          - "1.9.1-py3.9.12-cuda11.1-ubuntu20.04"
          - "1.10.2-py3.9.12-cuda11.3.1-ubuntu20.04"
          - "1.11.0-py3.9.12-cuda11.3.1-ubuntu20.04"
          - "1.12.1-py3.9.12-cuda11.6.2-ubuntu20.04"

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          MOIRAI_VERSION=$(cd moirai && python -c "from version import __version__; print(__version__)")
          echo "MOIRAI_VERSION=$MOIRAI_VERSION" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ matrix.base-image-tag }}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg IMAGE_TAG=${IMAGE_TAG} \
            -t dunzane/pipeai:${MOIRAI_VERSION}-${IMAGE_TAG} \
            -t dunzane/pipeai:latest-${IMAGE_TAG} \
            -f docker/dev/Dockerfile \
            .

      - name: Push Docker image
        run: |
          docker push dunzane/pipeai:${MOIRAI_VERSION}-${IMAGE_TAG}
          docker push dunzane/pipeai:latest-${IMAGE_TAG}