name: PyPI Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')

  steps:
  - uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.10"

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install hatch build twine
  
  - name: Build package
    run: |
      rm -rf dist/
      hatch build

  - name: Publish to PyPI
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      password: ${{ secrets.PYPI_TOKEN }}
